/**
 * extract-diagrams.ts
 *
 * Generates architecture diagrams from the source code itself — no LLM.
 *
 *   - Module dependency graph (per source root) via dependency-cruiser.
 *   - React component tree (frontend only) via ts-morph JSX walking.
 *   - Folder-level subgraphs that drop into each folder's overview.md.
 *
 * Output: .mmd Mermaid files under _docs-out/<root>/_diagrams/. The LLM
 * pipeline includes these via Markdown ```mermaid blocks; it never edits
 * the .mmd files directly. They are auto-regenerated on every run, so the
 * diagrams are always current with the code.
 */

import { spawnSync } from 'node:child_process'
import fs from 'node:fs'
import path from 'node:path'
import { Project, Node, type SourceFile, SyntaxKind } from 'ts-morph'

import { repoRoot, sourceRoots, outputRoot } from './config.ts'

function ensureDir(dir: string): void {
  fs.mkdirSync(dir, { recursive: true })
}

interface DepCruiseModule {
  source: string
  dependencies: Array<{ resolved: string; module: string; coreModule?: boolean; couldNotResolve?: boolean }>
}

interface DepCruiseResult {
  modules: DepCruiseModule[]
}

function runDepCruise(absSourceDir: string): DepCruiseResult | null {
  // Invoke dependency-cruiser as a subprocess so we don't pull its
  // (large) public API into this module's type surface.
  const bin = path.resolve(repoRoot, 'scripts', 'docs', 'node_modules', '.bin', 'depcruise')
  if (!fs.existsSync(bin)) {
    console.warn(`dependency-cruiser binary not found at ${bin}; run npm install in scripts/docs first.`)
    return null
  }
  // depcruise needs an explicit glob; a bare directory yields zero modules.
  const relSource = path.relative(repoRoot, absSourceDir)
  const result = spawnSync(
    bin,
    [
      '--output-type', 'json',
      '--no-config',
      '--ts-pre-compilation-deps',
      '--exclude', '(node_modules|\\.test\\.|\\.spec\\.|__tests__)',
      `${relSource}/**/*`,
    ],
    { encoding: 'utf-8', maxBuffer: 50 * 1024 * 1024, cwd: repoRoot },
  )
  if (result.status !== 0) {
    console.warn(`dependency-cruiser failed for ${absSourceDir}:\n${result.stderr}`)
    return null
  }
  try {
    return JSON.parse(result.stdout) as DepCruiseResult
  } catch (err) {
    console.warn(`Could not parse dependency-cruiser output for ${absSourceDir}: ${(err as Error).message}`)
    return null
  }
}

function mermaidId(p: string): string {
  // Mermaid node IDs cannot have slashes, dots, or hyphens at certain positions.
  return p.replace(/[^a-zA-Z0-9_]/g, '_')
}

function renderDepGraph(rootName: string, absSourceDir: string, modules: DepCruiseModule[]): string {
  const lines: string[] = []
  lines.push(`%% Module dependency graph for ${rootName}`)
  lines.push(`%% Auto-generated by scripts/docs/extract-diagrams.ts. Do not edit.`)
  lines.push('flowchart LR')
  const seen = new Set<string>()
  const edges: string[] = []
  for (const m of modules) {
    const src = path.relative(absSourceDir, path.resolve(repoRoot, m.source))
    if (src.startsWith('..')) continue
    const srcId = mermaidId(src)
    if (!seen.has(srcId)) {
      lines.push(`  ${srcId}["${src}"]`)
      seen.add(srcId)
    }
    for (const dep of m.dependencies) {
      if (dep.coreModule || dep.couldNotResolve) continue
      const depResolved = path.relative(absSourceDir, path.resolve(repoRoot, dep.resolved))
      if (depResolved.startsWith('..')) continue
      const depId = mermaidId(depResolved)
      if (!seen.has(depId)) {
        lines.push(`  ${depId}["${depResolved}"]`)
        seen.add(depId)
      }
      edges.push(`  ${srcId} --> ${depId}`)
    }
  }
  lines.push(...edges)
  return lines.join('\n') + '\n'
}

function renderFolderSubgraph(
  rootName: string,
  folder: string,
  absSourceDir: string,
  modules: DepCruiseModule[],
): string | null {
  const inFolder = (rel: string) => rel === folder || rel.startsWith(folder + path.sep)
  const relevant = modules
    .map((m) => ({
      source: path.relative(absSourceDir, path.resolve(repoRoot, m.source)),
      deps: m.dependencies
        .filter((d) => !d.coreModule && !d.couldNotResolve)
        .map((d) => path.relative(absSourceDir, path.resolve(repoRoot, d.resolved))),
    }))
    .filter((m) => inFolder(m.source))
  if (relevant.length === 0) return null
  const lines: string[] = []
  lines.push(`%% Subgraph for ${rootName}/${folder}`)
  lines.push(`%% Auto-generated by scripts/docs/extract-diagrams.ts. Do not edit.`)
  lines.push('flowchart LR')
  const seen = new Set<string>()
  for (const m of relevant) {
    const id = mermaidId(m.source)
    if (!seen.has(id)) {
      lines.push(`  ${id}["${m.source}"]`)
      seen.add(id)
    }
    for (const dep of m.deps) {
      const depId = mermaidId(dep)
      if (!seen.has(depId)) {
        const label = inFolder(dep) ? dep : `external: ${dep}`
        lines.push(`  ${depId}["${label}"]`)
        seen.add(depId)
      }
      lines.push(`  ${id} --> ${depId}`)
    }
  }
  return lines.join('\n') + '\n'
}

/**
 * React component tree. We look for JSX usage of locally-imported identifiers
 * to build a parent → child graph. Heuristic but deterministic and matches
 * real component composition closely enough to be valuable.
 */
function renderComponentTree(absSourceDir: string): string | null {
  const tsxFiles: string[] = []
  function walk(dir: string): void {
    for (const entry of fs.readdirSync(dir, { withFileTypes: true })) {
      const full = path.join(dir, entry.name)
      if (entry.isDirectory()) {
        if (entry.name === 'node_modules' || entry.name === '__tests__') continue
        walk(full)
      } else if (
        entry.name.endsWith('.tsx') &&
        !entry.name.endsWith('.test.tsx') &&
        !entry.name.endsWith('.spec.tsx')
      ) {
        tsxFiles.push(full)
      }
    }
  }
  if (!fs.existsSync(absSourceDir)) return null
  walk(absSourceDir)
  if (tsxFiles.length === 0) return null

  const project = new Project({ skipAddingFilesFromTsConfig: true })
  for (const f of tsxFiles) project.addSourceFileAtPath(f)

  function fileComponentName(filePath: string): string {
    const base = path.basename(filePath).replace(/\.tsx$/, '')
    return base
  }

  const edges = new Set<string>()
  const nodes = new Set<string>()
  for (const sf of project.getSourceFiles()) {
    const parent = fileComponentName(sf.getFilePath())
    nodes.add(parent)
    // Local imports: capture default + named imports from relative paths.
    const localImports = new Map<string, string>() // local-name -> imported file basename
    for (const imp of sf.getImportDeclarations()) {
      const mod = imp.getModuleSpecifierValue()
      if (!mod.startsWith('.')) continue
      const resolvedFile = imp.getModuleSpecifierSourceFile()
      const importedFromBase = resolvedFile
        ? fileComponentName(resolvedFile.getFilePath())
        : path.basename(mod)
      const def = imp.getDefaultImport()
      if (def) localImports.set(def.getText(), importedFromBase)
      for (const ni of imp.getNamedImports()) {
        localImports.set(ni.getName(), importedFromBase)
      }
    }
    // Find JSX element usages.
    sf.forEachDescendant((node) => {
      if (
        node.getKind() === SyntaxKind.JsxOpeningElement ||
        node.getKind() === SyntaxKind.JsxSelfClosingElement
      ) {
        const name = (node as unknown as { getTagNameNode(): Node }).getTagNameNode().getText()
        if (/^[A-Z]/.test(name) && localImports.has(name)) {
          const child = localImports.get(name)!
          if (child !== parent) {
            nodes.add(child)
            edges.add(`${parent}-->${child}`)
          }
        }
      }
    })
  }
  if (edges.size === 0) return null
  const lines: string[] = []
  lines.push('%% React component tree (parent renders child)')
  lines.push('%% Auto-generated by scripts/docs/extract-diagrams.ts. Do not edit.')
  lines.push('flowchart TD')
  for (const n of nodes) lines.push(`  ${mermaidId(n)}["${n}"]`)
  for (const e of edges) {
    const [from, to] = e.split('-->')
    lines.push(`  ${mermaidId(from)} --> ${mermaidId(to)}`)
  }
  return lines.join('\n') + '\n'
}

function topLevelFolders(absSourceDir: string): string[] {
  if (!fs.existsSync(absSourceDir)) return []
  return fs
    .readdirSync(absSourceDir, { withFileTypes: true })
    .filter((e) => e.isDirectory() && !e.name.startsWith('.') && e.name !== 'node_modules' && e.name !== '__tests__')
    .map((e) => e.name)
}

async function run(): Promise<void> {
  for (const root of sourceRoots) {
    const absSourceDir = path.resolve(repoRoot, root.sourceDir)
    if (!fs.existsSync(absSourceDir)) continue
    const outDir = path.join(outputRoot, root.outDir, '_diagrams')
    ensureDir(outDir)
    const cruise = runDepCruise(absSourceDir)
    if (cruise) {
      const fullGraph = renderDepGraph(root.name, absSourceDir, cruise.modules)
      fs.writeFileSync(path.join(outDir, 'deps.mmd'), fullGraph, 'utf-8')
      console.log(`✓ ${root.name}/deps.mmd  (${cruise.modules.length} modules)`)
      for (const folder of topLevelFolders(absSourceDir)) {
        const sub = renderFolderSubgraph(root.name, folder, absSourceDir, cruise.modules)
        if (sub) {
          const folderOut = path.join(outputRoot, root.outDir, folder, '_diagrams')
          ensureDir(folderOut)
          fs.writeFileSync(path.join(folderOut, 'deps.mmd'), sub, 'utf-8')
          console.log(`✓ ${root.name}/${folder}/deps.mmd`)
        }
      }
    }
    if (root.name === 'frontend') {
      const tree = renderComponentTree(absSourceDir)
      if (tree) {
        fs.writeFileSync(path.join(outDir, 'component-tree.mmd'), tree, 'utf-8')
        console.log(`✓ ${root.name}/component-tree.mmd`)
      }
    }
  }
}

run().catch((err) => {
  console.error(err)
  process.exit(1)
})
